sonar.projectKey=collapseeee_SE327-project-mouse-jerry
sonar.organization=collapseeee
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.ts,**/*.spec.ts,**/*.test.ts
